site_name: Starlette-Login
site_description: User session management for Starlette

theme:
  name: 'material'
#  custom_dir: docs/overrides
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'

repo_name: jockerz/Starlette-Login
repo_url: https://github.com/jockerz/Starlette-Login
edit_uri: ""

nav:
  - Starlette-Login: index.md
  - Configuration: configuration.md
  - Login Manager: login-manager.md
  - Tutorial:
    - tutorial/index.md
  - Advance:
    - advance/index.md
  - Contribution: contribution.md
